
#数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pro?useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
#防止端口冲突
server:
  port: 8005
dubbo:
  application:
    #应用名称
    name: consumer
  registry:
    #注册中心地址
    address: zookeeper://localhost:2181
    timeout: 30000